services:
    accounting-nginx:
        container_name: accounting-nginx
        build: ./docker/nginx
        volumes:
            - .:/var/www/html
        ports:
            - 80:80

    accounting-php:
        container_name: accounting-php
        build: ./docker/php
        ports:
            - 9000:9000
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini

    accounting-pgsql:
        container_name: accounting-pgsql
        build: docker/postgresql
        environment:
            POSTGRES_DB: accounting_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./docker/postgresql/data:/var/lib/postgresql
